= RockyCoastCRN
Martin Hurst <mhurst@bgs.ac.uk>
v0.0.1 2016-04-25
:toc: left
:numbered:
:stem: latexmath

Welcome to the website for RockyCoastCRN, a model simulating the accumulation of cosmogenic radionculides (CRNs) in an evolving shore platform.

http://martinhurst.com[Click here] to return to my homepage.

== Introduction
RockyCoastCRN is a numerical model simulating the evolution of a coastal profile (cliff and shore platform) through time and predicting the concentration of cosmogenic radionuclides (CRNs; e.g. ^10^Be) that accumulate in the shore platform.

The model was presented in a paper on modelling the accumulation of CRNs in shore platforms, and a second paper on application to derive rates of coastal cliff retreat on the coast of East Sussex, UK. Links to these papers will be added to the website as soon as they are published.

The model is intended for research purposes. It is released under a http://www.gnu.org/licenses/gpl-3.0.en.html[GNU General Public Licence]. If you are interesting in working with RockyCoastCRN I would encourage you to get in touch and work collaboratively.

== Getting Started
This code has been written in a Linux environment, and has not been tested on Mac or Windows (yet). The code is documented using Doxygen and the resulting documentation can be accessed at the RockyCoastCRN Doxygen Documentation page (link will be added later).

=== Download the model
The model can be downloaded as a zip or tar.gz from the following link (insert link). Once downloaded, extract the contents to an appropriate workspace. Alternatively, the model can be downloaded from the github release page (add link). Links will be added once a release version has been finalised.

=== Compiling the code
The code can be compiled in a Linux environment from the command line, using one of the makefiles. These are contained in the "driver_files" subdirectory. The driver files are C++ scripts that control the initiation, running and saving of a RockyCoastCRN model run. There are multiple driver files associated with various experiments published in the relevant publications. In this tutorial we will use the example for simulating platform evolution by step-backwear.

In a terminal, navigate to the driver_file subdirectory

[source]
----
RockyCoastCRN$ cd driver_files
----

Compile RockyCoastCRN for evolving the CRN concentration in a stepped shore platform by launching the makefile:

[source]
----
RockyCoastCRN/driver_files$ make -f stepped_platform_make.make
----

This will create an executable stepped_platform.out which can be launched from the command line to run the model. First, let's move the executable to the parent directory, and navigate to the same directory:

[source]
----
COVE/driver_files$ mv stepped_platform.out
COVE/driver_files$ cd ..
----

=== Running the model

The file stepped_platform.out generated by compiling the code can be launched from the command line:

[source]
----
COVE/driver_files$ ./spiral_bay.out
----

Running it in this way may result in it terminating with an error, which will tell you that the program requires a number of input arguments in order to run.

I plot of the resulting model output using the python matplotlib library. To use them you will need a python IDE such as Spyder. A series of plotting functions are included in the subdirectory plotting_functions. To plot the results of your stepped platform model run, open the file plot_stepped_platform.py in your favourite python IDE, and run. You should get the following figure:

Add example figure here.
